-- Bootstrap role: SYSADMIN. KPI_PLATFORM_ADMIN must already be granted to SYSADMIN.
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS KPI_INTELLIGENCE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_RESUME = TRUE
    AUTO_SUSPEND = 60
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Development compute for the Enterprise KPI lighthouse';

ALTER WAREHOUSE KPI_INTELLIGENCE_WH SET
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_RESUME = TRUE
    AUTO_SUSPEND = 60
    COMMENT = 'Development compute for the Enterprise KPI lighthouse';

GRANT OWNERSHIP ON WAREHOUSE KPI_INTELLIGENCE_WH
    TO ROLE KPI_PLATFORM_ADMIN;
