-- Object grants are controlled by the database and managed-schema owner.
USE ROLE KPI_PLATFORM_ADMIN;

-- Development compute. Executive access is agent-mediated and receives no warehouse grant.
GRANT USAGE ON WAREHOUSE KPI_INTELLIGENCE_WH TO ROLE KPI_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE KPI_INTELLIGENCE_WH TO ROLE KPI_SEMANTIC_ENGINEER;
GRANT USAGE ON WAREHOUSE KPI_INTELLIGENCE_WH TO ROLE KPI_AI_BUILDER;
GRANT USAGE ON WAREHOUSE KPI_INTELLIGENCE_WH TO ROLE KPI_AI_RUNTIME;
GRANT USAGE ON WAREHOUSE KPI_INTELLIGENCE_WH TO ROLE KPI_AUDITOR;

GRANT USAGE ON DATABASE KPI_INTELLIGENCE_DB TO ROLE KPI_DATA_ENGINEER;
GRANT USAGE ON DATABASE KPI_INTELLIGENCE_DB TO ROLE KPI_SEMANTIC_ENGINEER;
GRANT USAGE ON DATABASE KPI_INTELLIGENCE_DB TO ROLE KPI_AI_BUILDER;
GRANT USAGE ON DATABASE KPI_INTELLIGENCE_DB TO ROLE KPI_AI_RUNTIME;
GRANT USAGE ON DATABASE KPI_INTELLIGENCE_DB TO ROLE KPI_AUDITOR;

-- Data Engineer: RAW/TRUSTED build boundary only.
GRANT USAGE ON SCHEMA KPI_INTELLIGENCE_DB.RAW TO ROLE KPI_DATA_ENGINEER;
GRANT USAGE ON SCHEMA KPI_INTELLIGENCE_DB.TRUSTED TO ROLE KPI_DATA_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA KPI_INTELLIGENCE_DB.RAW TO ROLE KPI_DATA_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW
    ON SCHEMA KPI_INTELLIGENCE_DB.TRUSTED TO ROLE KPI_DATA_ENGINEER;

-- Semantic Engineer: trusted/governance read boundary and semantic namespace usage.
GRANT USAGE ON SCHEMA KPI_INTELLIGENCE_DB.TRUSTED TO ROLE KPI_SEMANTIC_ENGINEER;
GRANT USAGE ON SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_SEMANTIC_ENGINEER;
GRANT USAGE ON SCHEMA KPI_INTELLIGENCE_DB.SEMANTIC TO ROLE KPI_SEMANTIC_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA KPI_INTELLIGENCE_DB.TRUSTED TO ROLE KPI_SEMANTIC_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA KPI_INTELLIGENCE_DB.TRUSTED TO ROLE KPI_SEMANTIC_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA KPI_INTELLIGENCE_DB.TRUSTED TO ROLE KPI_SEMANTIC_ENGINEER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KPI_INTELLIGENCE_DB.TRUSTED TO ROLE KPI_SEMANTIC_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_SEMANTIC_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_SEMANTIC_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_SEMANTIC_ENGINEER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_SEMANTIC_ENGINEER;

-- AI Builder: namespace usage only until current Cortex object privileges are verified.
GRANT USAGE ON SCHEMA KPI_INTELLIGENCE_DB.AI TO ROLE KPI_AI_BUILDER;
GRANT USAGE ON SCHEMA KPI_INTELLIGENCE_DB.SEMANTIC TO ROLE KPI_AI_BUILDER;
GRANT USAGE ON SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_AI_BUILDER;
GRANT SELECT ON ALL TABLES IN SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_AI_BUILDER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_AI_BUILDER;
GRANT SELECT ON ALL VIEWS IN SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_AI_BUILDER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_AI_BUILDER;

-- AI Runtime: namespace and compute usage only; no CREATE, DML, or ownership.
GRANT USAGE ON SCHEMA KPI_INTELLIGENCE_DB.AI TO ROLE KPI_AI_RUNTIME;
GRANT USAGE ON SCHEMA KPI_INTELLIGENCE_DB.SEMANTIC TO ROLE KPI_AI_RUNTIME;
GRANT USAGE ON SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_AI_RUNTIME;

-- Executive is intentionally a role-only, agent-consumption persona at foundation stage.

-- Auditor: read-only governance and audit boundary.
GRANT USAGE ON SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_AUDITOR;
GRANT USAGE ON SCHEMA KPI_INTELLIGENCE_DB.AUDIT TO ROLE KPI_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_AUDITOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_AUDITOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_AUDITOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KPI_INTELLIGENCE_DB.GOVERNANCE TO ROLE KPI_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA KPI_INTELLIGENCE_DB.AUDIT TO ROLE KPI_AUDITOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA KPI_INTELLIGENCE_DB.AUDIT TO ROLE KPI_AUDITOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA KPI_INTELLIGENCE_DB.AUDIT TO ROLE KPI_AUDITOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KPI_INTELLIGENCE_DB.AUDIT TO ROLE KPI_AUDITOR;
