-- Verification role: KPI_PLATFORM_ADMIN. This script is read-only.
USE ROLE KPI_PLATFORM_ADMIN;
USE WAREHOUSE KPI_INTELLIGENCE_WH;

SHOW ROLES;
SELECT
    'APPROVED_ROLE_COUNT' AS check_name,
    IFF(COUNT_IF("name" IN (
        'KPI_PLATFORM_ADMIN', 'KPI_DATA_ENGINEER', 'KPI_SEMANTIC_ENGINEER',
        'KPI_AI_BUILDER', 'KPI_AI_RUNTIME', 'KPI_EXECUTIVE', 'KPI_AUDITOR'
    )) = 7, 'PASS', 'FAIL') AS status,
    COUNT_IF("name" IN (
        'KPI_PLATFORM_ADMIN', 'KPI_DATA_ENGINEER', 'KPI_SEMANTIC_ENGINEER',
        'KPI_AI_BUILDER', 'KPI_AI_RUNTIME', 'KPI_EXECUTIVE', 'KPI_AUDITOR'
    )) AS observed_project_roles
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW GRANTS OF ROLE KPI_DATA_ENGINEER;
SELECT 'KPI_DATA_ENGINEER_PARENT' AS check_name,
       IFF(COUNT_IF("granted_to" = 'ROLE' AND "grantee_name" = 'KPI_PLATFORM_ADMIN') = 1, 'PASS', 'FAIL') AS status
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW GRANTS OF ROLE KPI_SEMANTIC_ENGINEER;
SELECT 'KPI_SEMANTIC_ENGINEER_PARENT' AS check_name,
       IFF(COUNT_IF("granted_to" = 'ROLE' AND "grantee_name" = 'KPI_PLATFORM_ADMIN') = 1, 'PASS', 'FAIL') AS status
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW GRANTS OF ROLE KPI_AI_BUILDER;
SELECT 'KPI_AI_BUILDER_PARENT' AS check_name,
       IFF(COUNT_IF("granted_to" = 'ROLE' AND "grantee_name" = 'KPI_PLATFORM_ADMIN') = 1, 'PASS', 'FAIL') AS status
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW GRANTS OF ROLE KPI_AI_RUNTIME;
SELECT 'KPI_AI_RUNTIME_PARENT' AS check_name,
       IFF(COUNT_IF("granted_to" = 'ROLE' AND "grantee_name" = 'KPI_PLATFORM_ADMIN') = 1, 'PASS', 'FAIL') AS status
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW GRANTS OF ROLE KPI_EXECUTIVE;
SELECT 'KPI_EXECUTIVE_PARENT' AS check_name,
       IFF(COUNT_IF("granted_to" = 'ROLE' AND "grantee_name" = 'KPI_PLATFORM_ADMIN') = 1, 'PASS', 'FAIL') AS status
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW GRANTS OF ROLE KPI_AUDITOR;
SELECT 'KPI_AUDITOR_PARENT' AS check_name,
       IFF(COUNT_IF("granted_to" = 'ROLE' AND "grantee_name" = 'KPI_PLATFORM_ADMIN') = 1, 'PASS', 'FAIL') AS status
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW GRANTS OF ROLE KPI_PLATFORM_ADMIN;
SELECT 'KPI_PLATFORM_ADMIN_PARENT' AS check_name,
       IFF(COUNT_IF("granted_to" = 'ROLE' AND "grantee_name" = 'SYSADMIN') = 1, 'PASS', 'FAIL') AS status
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW WAREHOUSES LIKE 'KPI_INTELLIGENCE_WH';
SELECT
    'WAREHOUSE_CONFIGURATION' AS check_name,
    IFF(
        COUNT_IF(
            "name" = 'KPI_INTELLIGENCE_WH'
            AND "size" = 'X-Small'
            AND "auto_suspend" = 60
            AND "auto_resume" = 'true'
            AND "min_cluster_count" = 1
            AND "max_cluster_count" = 1
            AND "owner" = 'KPI_PLATFORM_ADMIN'
        ) = 1,
        'PASS', 'FAIL'
    ) AS status
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW DATABASES LIKE 'KPI_INTELLIGENCE_DB';
SELECT
    'DATABASE_OWNERSHIP' AS check_name,
    IFF(COUNT_IF("name" = 'KPI_INTELLIGENCE_DB' AND "owner" = 'KPI_PLATFORM_ADMIN') = 1, 'PASS', 'FAIL') AS status
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW SCHEMAS IN DATABASE KPI_INTELLIGENCE_DB;
SELECT
    'APPROVED_SCHEMA_SET' AS check_name,
    IFF(
        COUNT_IF("name" <> 'INFORMATION_SCHEMA') = 6
        AND COUNT_IF("name" IN ('RAW', 'TRUSTED', 'GOVERNANCE', 'SEMANTIC', 'AI', 'AUDIT')) = 6,
        'PASS', 'FAIL'
    ) AS status,
    COUNT_IF("name" <> 'INFORMATION_SCHEMA') AS observed_project_schemas
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW SCHEMAS IN DATABASE KPI_INTELLIGENCE_DB;
SELECT
    'SCHEMA_OWNERSHIP' AS check_name,
    IFF(
        COUNT_IF(
            "name" IN ('RAW', 'TRUSTED', 'GOVERNANCE', 'SEMANTIC', 'AI', 'AUDIT')
            AND "owner" = 'KPI_PLATFORM_ADMIN'
        ) = 6,
        'PASS', 'FAIL'
    ) AS status
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW GRANTS TO ROLE KPI_AI_RUNTIME;
SELECT
    'AI_RUNTIME_NO_BUILD_OR_DML' AS check_name,
    IFF(COUNT_IF("privilege" IN (
        'OWNERSHIP', 'CREATE TABLE', 'CREATE VIEW', 'CREATE STAGE', 'CREATE FILE FORMAT',
        'INSERT', 'UPDATE', 'DELETE', 'TRUNCATE'
    )) = 0, 'PASS', 'FAIL') AS status
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW GRANTS TO ROLE KPI_EXECUTIVE;
SELECT
    'EXECUTIVE_AGENT_ONLY_FOUNDATION' AS check_name,
    IFF(
        COALESCE(COUNT_IF("granted_on" IN ('WAREHOUSE', 'DATABASE', 'SCHEMA')), 0) = 0,
        'PASS', 'FAIL'
    ) AS status
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW GRANTS TO ROLE KPI_AUDITOR;
SELECT
    'AUDITOR_NO_DML' AS check_name,
    IFF(COUNT_IF("privilege" IN ('INSERT', 'UPDATE', 'DELETE', 'TRUNCATE')) = 0, 'PASS', 'FAIL') AS status
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW GRANTS TO ROLE KPI_DATA_ENGINEER;
SELECT
    'DATA_ENGINEER_NO_ACCOUNT_PRIVILEGES' AS check_name,
    IFF(COUNT_IF("granted_on" = 'ACCOUNT') = 0, 'PASS', 'FAIL') AS status
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
