-- ============================================================================
-- Enterprise AI Knowledge Platform
-- PROCESSED Schema Tables
-- ============================================================================

USE ROLE CORTEX_AI_ADMIN;
USE DATABASE CORTEX_AI_PLATFORM;
USE SCHEMA PROCESSED;

-- Parsed document content from AI_PARSE_DOCUMENT
CREATE TABLE IF NOT EXISTS PARSED_DOCUMENTS (
    PARSE_ID            VARCHAR(50) NOT NULL DEFAULT UUID_STRING(),
    DOCUMENT_ID         VARCHAR(50) NOT NULL,
    PARSED_CONTENT      VARCHAR(16777216),
    CONTENT_TYPE        VARCHAR(20) DEFAULT 'TEXT',
    PAGE_COUNT          NUMBER(5),
    WORD_COUNT          NUMBER(10),
    PARSE_MODEL         VARCHAR(100),
    PARSE_DURATION_MS   NUMBER(10),
    PARSED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_PARSED_DOCUMENTS PRIMARY KEY (PARSE_ID),
    CONSTRAINT FK_PARSED_DOC_REGISTRY FOREIGN KEY (DOCUMENT_ID)
        REFERENCES CORTEX_AI_PLATFORM.RAW.DOCUMENT_REGISTRY(DOCUMENT_ID)
)
COMMENT = 'AI_PARSE_DOCUMENT output - full extracted text per document';

-- Document classifications
CREATE TABLE IF NOT EXISTS DOCUMENT_CLASSIFICATIONS (
    CLASSIFICATION_ID   VARCHAR(50) NOT NULL DEFAULT UUID_STRING(),
    DOCUMENT_ID         VARCHAR(50) NOT NULL,
    DEPARTMENT          VARCHAR(50) NOT NULL,
    DOCUMENT_TYPE       VARCHAR(50),
    SENSITIVITY_LEVEL   VARCHAR(20) DEFAULT 'INTERNAL',
    TOPICS              ARRAY,
    CONFIDENCE_SCORE    FLOAT,
    CLASSIFICATION_MODEL VARCHAR(100),
    CLASSIFIED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DOCUMENT_CLASSIFICATIONS PRIMARY KEY (CLASSIFICATION_ID),
    CONSTRAINT FK_CLASS_DOC_REGISTRY FOREIGN KEY (DOCUMENT_ID)
        REFERENCES CORTEX_AI_PLATFORM.RAW.DOCUMENT_REGISTRY(DOCUMENT_ID)
)
COMMENT = 'AI-driven document classification results';

-- Extracted metadata (key-value pairs per document)
CREATE TABLE IF NOT EXISTS DOCUMENT_METADATA (
    METADATA_ID         VARCHAR(50) NOT NULL DEFAULT UUID_STRING(),
    DOCUMENT_ID         VARCHAR(50) NOT NULL,
    METADATA_KEY        VARCHAR(200) NOT NULL,
    METADATA_VALUE      VARCHAR(5000),
    EXTRACTION_METHOD   VARCHAR(50),
    CONFIDENCE          FLOAT,
    EXTRACTED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DOCUMENT_METADATA PRIMARY KEY (METADATA_ID),
    CONSTRAINT FK_META_DOC_REGISTRY FOREIGN KEY (DOCUMENT_ID)
        REFERENCES CORTEX_AI_PLATFORM.RAW.DOCUMENT_REGISTRY(DOCUMENT_ID)
)
COMMENT = 'Extracted metadata key-value pairs per document';

-- Processing audit trail
CREATE TABLE IF NOT EXISTS PROCESSING_LOG (
    LOG_ID              VARCHAR(50) NOT NULL DEFAULT UUID_STRING(),
    DOCUMENT_ID         VARCHAR(50) NOT NULL,
    STEP_NAME           VARCHAR(100) NOT NULL,
    STATUS              VARCHAR(20) NOT NULL,
    STARTED_AT          TIMESTAMP_NTZ,
    COMPLETED_AT        TIMESTAMP_NTZ,
    DURATION_MS         NUMBER(10),
    ERROR_MESSAGE       VARCHAR(5000),
    DETAILS             VARIANT,
    CONSTRAINT PK_PROCESSING_LOG PRIMARY KEY (LOG_ID)
)
COMMENT = 'Audit trail for each processing step per document';
