USE ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE STREAMING_DEMO TO ROLE STREAMING_ROLE;
GRANT USAGE ON SCHEMA STREAMING_DEMO.RAW TO ROLE STREAMING_ROLE;

GRANT INSERT, SELECT
    ON TABLE STREAMING_DEMO.RAW.IOT_EVENTS
    TO ROLE STREAMING_ROLE;

GRANT OPERATE
    ON PIPE STREAMING_DEMO.RAW.IOT_EVENTS_STREAMING
    TO ROLE STREAMING_ROLE;

-- Optional monitoring permission for operators.
GRANT MONITOR
    ON PIPE STREAMING_DEMO.RAW.IOT_EVENTS_STREAMING
    TO ROLE STREAMING_ROLE;
