USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE DBT_TRAINING_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE DBT_TRAINING;

CREATE OR REPLACE ROLE DBT_TRAINING_ROLE;

-- Replace with the Snowflake user who will run the workshop.
GRANT ROLE DBT_TRAINING_ROLE TO USER suvendu;

GRANT USAGE ON WAREHOUSE DBT_TRAINING_WH TO ROLE DBT_TRAINING_ROLE;
GRANT USAGE ON DATABASE DBT_TRAINING TO ROLE DBT_TRAINING_ROLE;

USE DATABASE DBT_TRAINING;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA TRAINING;
CREATE OR REPLACE SCHEMA TRAINING_STAGING;
CREATE OR REPLACE SCHEMA TRAINING_MARTS;
CREATE OR REPLACE SCHEMA TRAINING_REFERENCE;
CREATE OR REPLACE SCHEMA TRAINING_SNAPSHOTS;
CREATE OR REPLACE SCHEMA DBT_PROJECTS;

GRANT USAGE ON ALL SCHEMAS IN DATABASE DBT_TRAINING TO ROLE DBT_TRAINING_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE FUNCTION
  ON SCHEMA DBT_TRAINING.TRAINING TO ROLE DBT_TRAINING_ROLE;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA DBT_TRAINING.TRAINING_STAGING TO ROLE DBT_TRAINING_ROLE;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA DBT_TRAINING.TRAINING_MARTS TO ROLE DBT_TRAINING_ROLE;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA DBT_TRAINING.TRAINING_REFERENCE TO ROLE DBT_TRAINING_ROLE;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA DBT_TRAINING.TRAINING_SNAPSHOTS TO ROLE DBT_TRAINING_ROLE;
GRANT CREATE DBT PROJECT ON SCHEMA DBT_TRAINING.DBT_PROJECTS TO ROLE DBT_TRAINING_ROLE;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA DBT_TRAINING.RAW TO ROLE DBT_TRAINING_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DBT_TRAINING.RAW TO ROLE DBT_TRAINING_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DBT_TRAINING.TRAINING_STAGING TO ROLE DBT_TRAINING_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_TRAINING.TRAINING_MARTS TO ROLE DBT_TRAINING_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DBT_TRAINING.TRAINING_MARTS TO ROLE DBT_TRAINING_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_TRAINING.TRAINING_REFERENCE TO ROLE DBT_TRAINING_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_TRAINING.TRAINING_SNAPSHOTS TO ROLE DBT_TRAINING_ROLE;

USE WAREHOUSE DBT_TRAINING_WH;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE CUSTOMERS (
  CUSTOMER_ID NUMBER NOT NULL,
  CUSTOMER_NAME VARCHAR NOT NULL,
  SEGMENT VARCHAR NOT NULL,
  STATUS VARCHAR NOT NULL,
  CREATED_AT TIMESTAMP_NTZ NOT NULL,
  UPDATED_AT TIMESTAMP_NTZ NOT NULL,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO CUSTOMERS
  (CUSTOMER_ID, CUSTOMER_NAME, SEGMENT, STATUS, CREATED_AT, UPDATED_AT)
VALUES
  (1, 'Acme Health', 'Enterprise', 'ACTIVE', '2025-01-01 09:00:00', '2025-03-01 10:00:00'),
  (2, 'Blue Sky Retail', 'Mid-Market', 'ACTIVE', '2025-01-10 09:00:00', '2025-03-02 10:00:00'),
  (3, 'Cedar Financial', 'Enterprise', 'ACTIVE', '2025-01-20 09:00:00', '2025-03-03 10:00:00'),
  (4, 'Delta Foods', 'SMB', 'PROSPECT', '2025-02-01 09:00:00', '2025-03-04 10:00:00');

CREATE OR REPLACE TABLE ORDERS (
  ORDER_ID NUMBER NOT NULL,
  CUSTOMER_ID NUMBER NOT NULL,
  ORDER_DATE DATE NOT NULL,
  STATUS VARCHAR NOT NULL,
  UPDATED_AT TIMESTAMP_NTZ NOT NULL,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO ORDERS
  (ORDER_ID, CUSTOMER_ID, ORDER_DATE, STATUS, UPDATED_AT)
VALUES
  (1001, 1, '2025-03-01', 'COMPLETED', '2025-03-01 12:00:00'),
  (1002, 2, '2025-03-02', 'COMPLETED', '2025-03-02 12:00:00'),
  (1003, 1, '2025-03-03', 'COMPLETED', '2025-03-03 12:00:00'),
  (1004, 3, '2025-03-04', 'PENDING', '2025-03-04 12:00:00'),
  (1005, 4, '2025-03-05', 'CANCELLED', '2025-03-05 12:00:00');

CREATE OR REPLACE TABLE ORDER_ITEMS (
  ORDER_ID NUMBER NOT NULL,
  LINE_NUMBER NUMBER NOT NULL,
  PRODUCT_NAME VARCHAR NOT NULL,
  QUANTITY NUMBER NOT NULL,
  UNIT_PRICE NUMBER(12,2) NOT NULL,
  UPDATED_AT TIMESTAMP_NTZ NOT NULL,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO ORDER_ITEMS
  (ORDER_ID, LINE_NUMBER, PRODUCT_NAME, QUANTITY, UNIT_PRICE, UPDATED_AT)
VALUES
  (1001, 1, 'Analytics Starter', 2, 100.00, '2025-03-01 12:00:00'),
  (1001, 2, 'Data Quality Pack', 1, 400.00, '2025-03-01 12:00:00'),
  (1002, 1, 'Analytics Starter', 5, 100.00, '2025-03-02 12:00:00'),
  (1003, 1, 'Architecture Workshop', 1, 1200.00, '2025-03-03 12:00:00'),
  (1004, 1, 'Data Quality Pack', 2, 400.00, '2025-03-04 12:00:00'),
  (1005, 1, 'Analytics Starter', 1, 100.00, '2025-03-05 12:00:00');

SELECT * FROM CUSTOMERS ORDER BY CUSTOMER_ID;
SELECT * FROM ORDERS ORDER BY ORDER_ID;
SELECT * FROM ORDER_ITEMS ORDER BY ORDER_ID, LINE_NUMBER;
