-- Governance objects are owned by KPI_PLATFORM_ADMIN. Snowflake key constraints are
-- informational; 290_verify_kpi_registry.sql performs objective rule verification.
USE ROLE KPI_PLATFORM_ADMIN;
USE WAREHOUSE KPI_INTELLIGENCE_WH;
USE DATABASE KPI_INTELLIGENCE_DB;
USE SCHEMA GOVERNANCE;

CREATE TABLE IF NOT EXISTS KPI_REGISTRY (
    METRIC_ID VARCHAR NOT NULL,
    METRIC_VERSION NUMBER(10, 0) NOT NULL,
    METRIC_NAME VARCHAR NOT NULL,
    BUSINESS_DEFINITION VARCHAR NOT NULL,
    DOMAIN VARCHAR NOT NULL,
    OWNER_ROLE VARCHAR NOT NULL,
    STEWARD_ROLE VARCHAR NOT NULL,
    CALCULATION_DESCRIPTION VARCHAR NOT NULL,
    TRUSTED_SOURCE_RELATION VARCHAR NOT NULL,
    METRIC_AMOUNT_COLUMN VARCHAR NOT NULL,
    METRIC_DATE_COLUMN VARCHAR NOT NULL,
    CERTIFICATION_STATUS VARCHAR NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_TO DATE,
    APPROVAL_REFERENCE VARCHAR NOT NULL,
    BUSINESS_REASON VARCHAR NOT NULL,
    PREDECESSOR_METRIC_ID VARCHAR,
    PREDECESSOR_METRIC_VERSION NUMBER(10, 0),
    CREATED_AT TIMESTAMP_NTZ NOT NULL,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_KPI_REGISTRY PRIMARY KEY (METRIC_ID, METRIC_VERSION)
)
COMMENT = 'Versioned canonical KPI contracts, certification, ownership, and trusted calculation metadata';

CREATE TABLE IF NOT EXISTS KPI_SYNONYM (
    SYNONYM_ID VARCHAR NOT NULL,
    METRIC_ID VARCHAR NOT NULL,
    METRIC_VERSION NUMBER(10, 0) NOT NULL,
    SYNONYM VARCHAR NOT NULL,
    NORMALIZED_SYNONYM VARCHAR NOT NULL,
    SYNONYM_TYPE VARCHAR NOT NULL,
    CREATED_AT TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_KPI_SYNONYM PRIMARY KEY (SYNONYM_ID),
    CONSTRAINT FK_KPI_SYNONYM_REGISTRY FOREIGN KEY (METRIC_ID, METRIC_VERSION)
        REFERENCES KPI_REGISTRY (METRIC_ID, METRIC_VERSION)
)
COMMENT = 'Version-scoped approved vocabulary that legitimately identifies governed KPIs';

-- COMMONLY_CONFUSED_WITH is symmetric and is stored once per unordered KPI pair.
-- Conceptual uniqueness is evaluated with LEAST(source_metric_id, target_metric_id),
-- GREATEST(source_metric_id, target_metric_id), and relationship_type.
-- Relationship endpoints support explanation and discovery only. They never become
-- synonyms, candidate matches, ranking inputs, or automatic intent resolution.
CREATE TABLE IF NOT EXISTS KPI_RELATIONSHIP (
    RELATIONSHIP_ID VARCHAR NOT NULL,
    SOURCE_METRIC_ID VARCHAR NOT NULL,
    TARGET_METRIC_ID VARCHAR NOT NULL,
    RELATIONSHIP_TYPE VARCHAR NOT NULL,
    RELATIONSHIP_REASON VARCHAR NOT NULL,
    CREATED_AT TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_KPI_RELATIONSHIP PRIMARY KEY (RELATIONSHIP_ID)
)
COMMENT = 'Identity-level governed relationships between distinct canonical KPI concepts';

CREATE TABLE IF NOT EXISTS KPI_DECISION_PROVENANCE (
    PROVENANCE_ID VARCHAR NOT NULL,
    METRIC_ID VARCHAR NOT NULL,
    METRIC_VERSION NUMBER(10, 0) NOT NULL,
    DECISION_TYPE VARCHAR NOT NULL,
    DECISION_SUMMARY VARCHAR NOT NULL,
    RATIONALE VARCHAR NOT NULL,
    APPROVED_BY VARCHAR NOT NULL,
    APPROVAL_REFERENCE VARCHAR NOT NULL,
    DECISION_DATE DATE NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    SUPERSEDES_PROVENANCE_ID VARCHAR,
    CREATED_AT TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_KPI_DECISION_PROVENANCE PRIMARY KEY (PROVENANCE_ID),
    CONSTRAINT FK_KPI_PROVENANCE_REGISTRY FOREIGN KEY (METRIC_ID, METRIC_VERSION)
        REFERENCES KPI_REGISTRY (METRIC_ID, METRIC_VERSION)
)
COMMENT = 'Append-only business decision history explaining why governed KPI definitions exist';

-- Allowed certification lifecycle: DRAFT -> UNDER_REVIEW -> CERTIFIED -> DEPRECATED.
-- Allowed initial synonym types: CANONICAL_NAME and APPROVED_ALIAS.
-- Allowed initial relationship type: COMMONLY_CONFUSED_WITH.

-- Approved downstream roles receive read-only access to the governed metadata.
GRANT SELECT ON TABLE KPI_REGISTRY TO ROLE KPI_SEMANTIC_ENGINEER;
GRANT SELECT ON TABLE KPI_SYNONYM TO ROLE KPI_SEMANTIC_ENGINEER;
GRANT SELECT ON TABLE KPI_RELATIONSHIP TO ROLE KPI_SEMANTIC_ENGINEER;
GRANT SELECT ON TABLE KPI_DECISION_PROVENANCE TO ROLE KPI_SEMANTIC_ENGINEER;

GRANT SELECT ON TABLE KPI_REGISTRY TO ROLE KPI_AI_BUILDER;
GRANT SELECT ON TABLE KPI_SYNONYM TO ROLE KPI_AI_BUILDER;
GRANT SELECT ON TABLE KPI_RELATIONSHIP TO ROLE KPI_AI_BUILDER;
GRANT SELECT ON TABLE KPI_DECISION_PROVENANCE TO ROLE KPI_AI_BUILDER;

GRANT SELECT ON TABLE KPI_REGISTRY TO ROLE KPI_AUDITOR;
GRANT SELECT ON TABLE KPI_SYNONYM TO ROLE KPI_AUDITOR;
GRANT SELECT ON TABLE KPI_RELATIONSHIP TO ROLE KPI_AUDITOR;
GRANT SELECT ON TABLE KPI_DECISION_PROVENANCE TO ROLE KPI_AUDITOR;
