USE ROLE STREAMING_ROLE;

SELECT
    device_id,
    event_type,
    temperature,
    humidity,
    payload,
    ingested_at
FROM STREAMING_DEMO.RAW.IOT_EVENTS
ORDER BY ingested_at DESC;

SHOW PIPES LIKE 'IOT_EVENTS_STREAMING' IN SCHEMA STREAMING_DEMO.RAW;
SHOW CHANNELS IN PIPE STREAMING_DEMO.RAW.IOT_EVENTS_STREAMING;

-- Account Usage can have latency and may require an account-level monitoring role.
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.SNOWPIPE_STREAMING_CHANNEL_HISTORY
WHERE PIPE_NAME = 'IOT_EVENTS_STREAMING'
ORDER BY LAST_COMMITTED_TIME DESC;
