-- ============================================================================
-- Enterprise AI Knowledge Platform
-- Privilege Grants
-- ============================================================================

USE ROLE SECURITYADMIN;

-- Database usage
GRANT USAGE ON DATABASE CORTEX_AI_PLATFORM TO ROLE CORTEX_AI_ADMIN;
GRANT USAGE ON DATABASE CORTEX_AI_PLATFORM TO ROLE CORTEX_AI_SERVICE;
GRANT USAGE ON DATABASE CORTEX_AI_PLATFORM TO ROLE CORTEX_AI_USER;

-- Schema usage for ADMIN (all schemas)
GRANT USAGE ON ALL SCHEMAS IN DATABASE CORTEX_AI_PLATFORM TO ROLE CORTEX_AI_ADMIN;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE CORTEX_AI_PLATFORM TO ROLE CORTEX_AI_ADMIN;
GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE CORTEX_AI_PLATFORM TO ROLE CORTEX_AI_ADMIN;
GRANT CREATE STAGE ON ALL SCHEMAS IN DATABASE CORTEX_AI_PLATFORM TO ROLE CORTEX_AI_ADMIN;
GRANT CREATE TASK ON ALL SCHEMAS IN DATABASE CORTEX_AI_PLATFORM TO ROLE CORTEX_AI_ADMIN;
GRANT CREATE DYNAMIC TABLE ON ALL SCHEMAS IN DATABASE CORTEX_AI_PLATFORM TO ROLE CORTEX_AI_ADMIN;
GRANT CREATE FUNCTION ON ALL SCHEMAS IN DATABASE CORTEX_AI_PLATFORM TO ROLE CORTEX_AI_ADMIN;
GRANT CREATE PROCEDURE ON ALL SCHEMAS IN DATABASE CORTEX_AI_PLATFORM TO ROLE CORTEX_AI_ADMIN;

-- Schema usage for SERVICE
GRANT USAGE ON SCHEMA CORTEX_AI_PLATFORM.RAW TO ROLE CORTEX_AI_SERVICE;
GRANT USAGE ON SCHEMA CORTEX_AI_PLATFORM.PROCESSED TO ROLE CORTEX_AI_SERVICE;
GRANT USAGE ON SCHEMA CORTEX_AI_PLATFORM.KNOWLEDGE TO ROLE CORTEX_AI_SERVICE;
GRANT USAGE ON SCHEMA CORTEX_AI_PLATFORM.AGENT TO ROLE CORTEX_AI_SERVICE;
GRANT USAGE ON SCHEMA CORTEX_AI_PLATFORM.OBSERVABILITY TO ROLE CORTEX_AI_SERVICE;

-- SERVICE can read/write data tables and execute tasks
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA CORTEX_AI_PLATFORM.RAW TO ROLE CORTEX_AI_SERVICE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA CORTEX_AI_PLATFORM.PROCESSED TO ROLE CORTEX_AI_SERVICE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA CORTEX_AI_PLATFORM.KNOWLEDGE TO ROLE CORTEX_AI_SERVICE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA CORTEX_AI_PLATFORM.AGENT TO ROLE CORTEX_AI_SERVICE;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA CORTEX_AI_PLATFORM.OBSERVABILITY TO ROLE CORTEX_AI_SERVICE;

-- SERVICE can use stages
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA CORTEX_AI_PLATFORM.RAW TO ROLE CORTEX_AI_SERVICE;

-- USER role: read-only on KNOWLEDGE and AGENT schemas
GRANT USAGE ON SCHEMA CORTEX_AI_PLATFORM.KNOWLEDGE TO ROLE CORTEX_AI_USER;
GRANT USAGE ON SCHEMA CORTEX_AI_PLATFORM.AGENT TO ROLE CORTEX_AI_USER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CORTEX_AI_PLATFORM.KNOWLEDGE TO ROLE CORTEX_AI_USER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CORTEX_AI_PLATFORM.AGENT TO ROLE CORTEX_AI_USER;

-- Warehouse grants
USE ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE CORTEX_AI_INGESTION_WH TO ROLE CORTEX_AI_SERVICE;
GRANT USAGE ON WAREHOUSE CORTEX_AI_SEARCH_WH TO ROLE CORTEX_AI_SERVICE;
GRANT USAGE ON WAREHOUSE CORTEX_AI_SEARCH_WH TO ROLE CORTEX_AI_USER;
GRANT USAGE ON WAREHOUSE CORTEX_AI_STREAMLIT_WH TO ROLE CORTEX_AI_USER;
GRANT USAGE ON WAREHOUSE CORTEX_AI_ANALYTICS_WH TO ROLE CORTEX_AI_ADMIN;
