-- DB & Schema
CREATE DATABASE IF NOT EXISTS AGENTIC_DB;
CREATE SCHEMA IF NOT EXISTS AGENTIC_DB.BANKING;

USE DATABASE AGENTIC_DB;
USE SCHEMA BANKING;

-- Transactions
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    TXN_ID STRING,
    ACCOUNT_ID STRING,
    AMOUNT FLOAT,
    TXN_TIME TIMESTAMP
);

INSERT INTO TRANSACTIONS VALUES
('T1','A1',10000,CURRENT_TIMESTAMP),
('T2','A2',250000,CURRENT_TIMESTAMP),
('T3','A3',900000,CURRENT_TIMESTAMP);

-- RAG table
CREATE TABLE IF NOT EXISTS BANKING_DOCS (
    ID STRING,
    CONTENT STRING
);

INSERT INTO BANKING_DOCS VALUES
('1','Transactions above 2 lakh indicate fraud risk'),
('2','High-risk customers must be monitored');